[project]
name = "erd-model"
version = "0.1.0"
description = "PySINDy / ROM fitting"
requires-python = ">=3.10"
dependencies = [
    "h5py>=3.15.1",
    "imageio>=2.37.0",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "PyYAML>=6.0.2",
    "pysindy[cvxpy]>=2.0.0",
]

[project.optional-dependencies]
jax = ["jax", "jaxlib"]    # if you later want differentiable variants

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
