# NOTE: do not use scientific notation for numeric literals (e.g. "1e-2" for 0.01)
name: burgers_rom_local
seed: 0
data:
  equation: burgers
  structure: grid
  resolution: high
  split: train
  n_trajectories: 1
  trajectory_ids: [1]
  data_path: null
  download_if_missing: false
  lookback: 199
  rollout: 198
  squeeze_lookback_dim: false
  time_stride: 1
  time_limit: null
pod:
  rank: 8
  energy_fraction: null
  center: true
deriv:
  method: finite_difference
  scheme: central
sindy:
  poly_order: 2
  enabled: true
  include_bias: false
  # optimizer: sr3
  # optimizer_params:
  #   threshold: 0.1
  #   nu: 0.808
  #   max_iter: 5000
  #   normalize_columns: true
  # optimizer: stlsq
  # optimizer_params:
  #   threshold: 0
  #   alpha: 0.05
  #   max_iter: 20
  #   normalize_columns: true
  # optimizer: ssr
  # optimizer_params:
  #   alpha: 0.05
  #   max_iter: 20
  #   normalize_columns: true
  # optimizer: frols
  # optimizer_params:
  #   kappa: null
  #   normalize_columns: true
  optimizer: trappingsr3
  optimizer_params:
    eta: 100
    threshold: 0.0500481029
    alpha: 100
    beta: 100
    max_iter: 80
    gamma: -0.1
    normalize_columns: true
  constrain_energy: false
  parallel: true
  parallel_procs: 2
outputs_dir: outputs
plots:
  enabled: true
  movie_3d_surface: true
  movie_3d_interp_factor: 3
  movie_3d_mode_contributions: true
  movie_3d_parallel: true
  movie_3d_parallel_procs: 12
  movie_3d_decomposition: true
  movie_3d_decomposition_show_titles: false
  movie_3d_reconstruction_comparison: true
  movie_chronos_comparison: true
  movie_3d_surface_with_state_matrix: true
  dynabench_comparison_timesteps: 30
  movie_3d_surface_clean: true